# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9becd95d383750f3d6f77081426b55b4bcb6079557e204adffafceea0cc5044e1f3d0702a161b215e64c4033f501a147fee4bfa43fc0b1c08c76aac82d3fcd0

test:
  secret_key_base: b2b631fe14bf1b41bf515584d0f161bb8c99e4a5092f1bc8f73ad949cd46fbef8ef213e31e238a4ede690171e211542e81a4d5017456287326dc18d37305be81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
